### ISSUE TITLE
Support for Centos 7?

### ISSUE THREAD

**Issue by evbo** [area-of-dev/MySQLWorkbench.AppImage#1]
Hi, very handy having this! Could you support building Centos 7 appimages by chance? This seems to work on later versions of GLIBC only.

**Comment by AlexWoroschilow** [comment]
Hi, i am glad you like it :)

>   Could you support building Centos 7 appimages by chance?

The oracle provide the builds only for RHEL 8,  check here https://dev.mysql.com/downloads/workbench/
The only way to support Centos 7 is to build it from the source code, and there is no guarantee it will work. The probability of the missing / outdated libraries is quite high. Considering all this and the EOL of the centos 7 in June 2024 i do not think it worth the effort, sorry

**Comment by evbo** [comment]
thanks, are you aware of any other MySQL clients with a GUI that might be simple enough to run on older systems like centos 7? Hopefully as appimages?

**Comment by AlexWoroschilow** [comment]
> thanks, are you aware of any other MySQL clients with a GUI that might be simple enough to run on older systems like centos 7? Hopefully as appimages?


You can try dbeaver. 

An appimage from the apprepo wouldn't work because it was bundled with some libraries from ubuntu 20.04, 
but the developers provide the distro-independent build (dbeaver-ce-22.1.5-linux.gtk.x86_64.tar.gz) which might work in centos 7. 

Check the releases:  https://github.com/dbeaver/dbeaver/releases
